#' childfree: Access and harmonize demographic data to study childfree individuals
#'
#' @description Reads demographic data from a variety of public data sources,
#'    extracting and harmonizing variables useful for the study of childfree
#'    individuals.
#'
#'    Data can be generated from:
#'    * UN Demographic and Health Surveys data using [dhs()]
#'    * Michigan State University State of the State data using [soss()]
#'    * US CDC National Survey of Family Growth data using [nsfg()]
#'
#' An introduction to the package is available using \href{../vignettes/childfree.html}{\code{vignette("childfree")}},
#'    and the detailed codebooks generated by these functions are available using \href{../vignettes/codebooks.html}{\code{vignette("codebooks")}},

#'
#' @docType package
#' @name childfree
NULL
